name: Libage

on:
  push:
    branches: [ master ]


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:

      - name: Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Build Libage
        run: make

      - name: Package
        run: python3 setup.py sdist bdist_wheel

      - name: ls
        run: ls -alh